export const fullSchedule = {
  'Entrance Zone': [
    { time: '11:00', type: 'Registration' },
    { time: '11:30', type: 'Registration' },
    { time: '12:00', type: 'Job Fair' },
    { time: '13:00', type: 'Job Fair' },
    { time: '14:00', type: 'Job Fair' },
    { time: '15:00', type: 'Job Fair' },
    { time: '16:00', type: 'Job Fair' },
    { time: '17:00', type: 'Job Fair' },
    { time: '18:00', type: 'Job Fair' },
    { time: '19:00', type: 'Job Fair' },
    { time: '20:00', type: 'Job Fair' },
    { time: '21:00', type: 'Job Fair' },
    { time: '22:00', type: 'Job Fair' },
  ],
  'Small Open Stage': [
    { time: '11:30', type: 'Opening' },
  ],
  'Central Zone': [
    { time: '11:30', type: 'Welcome Food' },
    { time: '12:30', type: 'Welcome Food' },
    { time: '13:30', type: 'Welcome Food' },
    { time: '14:30', type: 'Welcome Food' },
    { time: '15:30', type: 'Welcome Food' },
    { time: '17:00', type: 'Open Talk' },
    { time: '18:00', type: 'Open Talk' },
    { time: '19:00', type: 'Stand-up' },
  ],
  'Small Stage': [
    { time: '12:00', type: 'Talk' },
    { time: '13:00', type: 'Talk' },
    { time: '14:00', type: 'Talk' },
    { time: '15:00', type: 'Talk' },
    { time: '16:00', type: 'Talk' },
    { time: '16:30', type: 'Startup Section' },
    { time: '17:30', type: 'Startup Section' },
    { time: '18:30', type: 'Startup Section' },
  ],
  'Main Stage': [
    { time: '12:00', type: 'Talk' },
    { time: '13:00', type: 'Talk' },
    { time: '14:00', type: 'Talk' },
    { time: '15:00', type: 'Talk' },
    { time: '16:00', type: 'Talk' },
    { time: '16:30', type: 'Yandex' },
    { time: '17:30', type: 'Yandex' },
    { time: '18:30', type: 'Yandex' },
    { time: '19:00', type: 'Live Music' },
    { time: '20:00', type: 'Afterparty' },
    { time: '21:00', type: 'Afterparty' },
    { time: '22:00', type: 'Afterparty' },
  ],
  'Big Open Stage': [
    { time: '12:30', type: 'Expo' },
    { time: '13:00', type: 'BBQ' },
    { time: '14:00', type: 'Lunch' },
    { time: '15:00', type: 'Lunch' },
    { time: '16:00', type: 'Expo' },
    { time: '17:00', type: 'Pilaf' },
    { time: '18:00', type: 'BBQ' },
    { time: '19:00', type: 'Dinner' },
  ],
  'Appendix': [
    { time: '12:00', type: 'Hookah' },
    { time: '13:00', type: 'Hookah' },
    { time: '14:00', type: 'Hookah' },
    { time: '15:00', type: 'Hookah' },
    { time: '16:00', type: 'Hookah' },
    { time: '17:00', type: 'Hookah' },
    { time: '18:00', type: 'Hookah' },
    { time: '19:00', type: 'Hookah' },
    { time: '20:00', type: 'Hookah' },
    { time: '21:00', type: 'Hookah' },
    { time: '22:00', type: 'Hookah' },
  ],
};

export const timeBasedSchedule = {
  '11:00': [
    { stage: 'Entrance Zone', type: 'Registration' },
  ],
  '11:30': [
    { stage: 'Entrance Zone', type: 'Registration' },
    { stage: 'Central Zone', type: 'Welcome Food' },
  ],
  '12:00': [
    { stage: 'Small Stage', type: 'Opening' },
    { stage: 'Central Zone', type: 'Welcome Food' },
  ],
  '12:30': [
    { stage: 'Main Stage', type: 'Speaker' },
    { stage: 'Big Open Stage', type: 'Speaker' },
    { stage: 'Small Stage', type: 'Speaker' },
    { stage: 'Central Zone', type: 'Expo' },
    { stage: 'Appendix', type: 'Hookah' },
    { stage: 'Entrance Zone', type: 'Job fair' },
  ],
  '13:00': [
    { stage: 'Main Stage', type: 'Speaker' },
    { stage: 'Big Open Stage', type: 'Speaker' },
    { stage: 'Small Stage', type: 'Speaker' },
    { stage: 'Central Zone', type: 'Expo' },
    { stage: 'Central Zone', type: 'BBQ' },
    { stage: 'Appendix', type: 'Hookah' },
    { stage: 'Entrance Zone', type: 'Job fair' },
  ],
  '13:30': [
    { stage: 'Main Stage', type: 'Speaker' },
    { stage: 'Big Open Stage', type: 'Speaker' },
    { stage: 'Small Stage', type: 'Speaker' },
    { stage: 'Central Zone', type: 'Expo' },
    { stage: 'Central Zone', type: 'BBQ' },
    { stage: 'Appendix', type: 'Hookah' },
    { stage: 'Entrance Zone', type: 'Job fair' },
  ],
  '14:00': [
    { stage: 'Main Stage', type: 'Speaker' },
    { stage: 'Big Open Stage', type: 'Speaker' },
    { stage: 'Small Stage', type: 'Speaker' },
    { stage: 'Central Zone', type: 'Expo' },
    { stage: 'Central Zone', type: 'Lunch' },
    { stage: 'Appendix', type: 'Hookah' },
    { stage: 'Entrance Zone', type: 'Job fair' },
  ],
  '14:30': [
    { stage: 'Main Stage', type: 'Speaker' },
    { stage: 'Big Open Stage', type: 'Speaker' },
    { stage: 'Small Stage', type: 'Speaker' },
    { stage: 'Central Zone', type: 'Expo' },
    { stage: 'Central Zone', type: 'Lunch' },
    { stage: 'Appendix', type: 'Hookah' },
    { stage: 'Entrance Zone', type: 'Job fair' },
  ],
  '15:00': [
    { stage: 'Main Stage', type: 'Speaker' },
    { stage: 'Big Open Stage', type: 'Speaker' },
    { stage: 'Small Stage', type: 'Speaker' },
    { stage: 'Central Zone', type: 'Expo' },
    { stage: 'Central Zone', type: 'Lunch' },
    { stage: 'Appendix', type: 'Hookah' },
    { stage: 'Entrance Zone', type: 'Job fair' },
  ],
  '15:30': [
    { stage: 'Main Stage', type: 'Speaker' },
    { stage: 'Big Open Stage', type: 'Speaker' },
    { stage: 'Small Stage', type: 'Speaker' },
    { stage: 'Central Zone', type: 'Expo' },
    { stage: 'Central Zone', type: 'BBQ' },
    { stage: 'Appendix', type: 'Hookah' },
    { stage: 'Entrance Zone', type: 'Job fair' },
  ],
  '16:00': [
    { stage: 'Main Stage', type: 'Speaker' },
    { stage: 'Big Open Stage', type: 'Speaker' },
    { stage: 'Small Stage', type: 'Speaker' },
    { stage: 'Central Zone', type: 'Expo' },
    { stage: 'Central Zone', type: 'BBQ' },
    { stage: 'Appendix', type: 'Hookah' },
    { stage: 'Entrance Zone', type: 'Job fair' },
  ],
  '16:30': [
    { stage: 'Main Stage', type: 'Speaker' },
    { stage: 'Big Open Stage', type: 'Speaker' },
    { stage: 'Small Stage', type: 'Speaker' },
    { stage: 'Central Zone', type: 'Expo' },
    { stage: 'Central Zone', type: 'BBQ' },
    { stage: 'Appendix', type: 'Hookah' },
    { stage: 'Entrance Zone', type: 'Job fair' },
  ],
  '17:00': [
    { stage: 'Main Stage', type: 'Yandex' },
    { stage: 'Big Open Stage', type: 'Open Talk' },
    { stage: 'Small Stage', type: 'Startup section' },
    { stage: 'Central Zone', type: 'Expo' },
    { stage: 'Central Zone', type: 'Pilaf' },
    { stage: 'Appendix', type: 'Hookah' },
    { stage: 'Entrance Zone', type: 'Job fair' },
  ],
  '17:30': [
    { stage: 'Main Stage', type: 'Yandex' },
    { stage: 'Big Open Stage', type: 'Open Talk' },
    { stage: 'Small Stage', type: 'Startup section' },
    { stage: 'Central Zone', type: 'Expo' },
    { stage: 'Central Zone', type: 'Pilaf' },
    { stage: 'Appendix', type: 'Hookah' },
    { stage: 'Entrance Zone', type: 'Job fair' },
  ],
  '18:00': [
    { stage: 'Main Stage', type: 'Yandex' },
    { stage: 'Big Open Stage', type: 'Open Talk' },
    { stage: 'Small Stage', type: 'Startup section' },
    { stage: 'Central Zone', type: 'Expo' },
    { stage: 'Central Zone', type: 'BBQ' },
    { stage: 'Appendix', type: 'Hookah' },
    { stage: 'Entrance Zone', type: 'Job fair' },
  ],
  '18:30': [
    { stage: 'Main Stage', type: 'Yandex' },
    { stage: 'Big Open Stage', type: 'Open Talk' },
    { stage: 'Small Stage', type: 'Startup section' },
    { stage: 'Central Zone', type: 'Expo' },
    { stage: 'Central Zone', type: 'BBQ' },
    { stage: 'Appendix', type: 'Hookah' },
    { stage: 'Entrance Zone', type: 'Job fair' },
  ],
  '19:00': [
    { stage: 'Small Open Stage', type: 'Closing' },
    { stage: 'Central Zone', type: 'Dinner' },
    { stage: 'Appendix', type: 'Hookah' },
    { stage: 'Entrance Zone', type: 'Job fair' },
  ],
  '19:30': [
    { stage: 'Main Stage', type: 'Live Music' },
    { stage: 'Small Open Stage', type: 'Stand-up' },
    { stage: 'Central Zone', type: 'BBQ' },
    { stage: 'Appendix', type: 'Hookah' },
    { stage: 'Entrance Zone', type: 'Job fair' },
  ],
  '20:00': [
    { stage: 'Main Stage', type: 'Live Music' },
    { stage: 'Small Open Stage', type: 'Stand-up' },
  ],
  '21:00': [
    { stage: 'Main Stage', type: 'Afterparty with DJs' },
  ],
};

