export type Member = {
  name: string,
  photo: string,
  role: string,
  contacts: {
    telegram?: string,
    instagram?: string,
    linkedin?: string,
  } | null,
  description: string,
  avatar: string
  avatarHovered: string
}

export const members: Member[] = [
  {
    name: 'Viktoria Ermakova',
    role: 'Community Manager',
    photo: 'vika',
    contacts: {
      telegram: 'sample',
      instagram: 'sample',
      linkedin: 'sample',
    },
    description: 'If the community is an algorithm, she’s the key that makes it run!',
    avatar: 'vika1_ajkmma',
    avatarHovered: 'vika2_mhe1uj',
  },
  {
    name: 'Dmitrii Solomonov',
    role: 'Backend Developer',
    photo: 'dima',
    contacts: null,
    description: 'Keeping the sound crisp and the conversations sharp',
    avatar: 'dima1_qqmlw7',
    avatarHovered: 'dima2_tuuxhn',
  },
  {
    name: 'Leonid Safronov',
    role: 'iOS Developer',
    photo: 'IMG_1176_uodayi',
    contacts: null,
    description: 'Joined IT Connect team on the first weekend after arriving in Belgrade',
    avatar: 'leo1_yve4rt',
    avatarHovered: 'leo2_wwdjvk',
  },
  {
    name: 'Yulia Makutu',
    role: 'Backend Developer',
    photo: 'yulia',
    contacts: null,
    description: 'She doesn’t just raise funds—she raises the energy level too!',
    avatar: 'yulya1_t5ghwr',
    avatarHovered: 'yulya2_jndof8',
  },
  {
    name: 'Anton Klochkov',
    role: 'Digital Marketing Specialist',
    photo: 'anton',
    contacts: null,
    description: 'Your code might crash, but his photos are always flawless',
    avatar: 'anton1_nbrt3t',
    avatarHovered: 'anton2_hhf9uc',
  },
  {
    name: 'Elena Solomonova',
    role: 'UX/UI Designer',
    photo: 'lena',
    contacts: null,
    description: 'Making meetups look as cool as they feel',
    avatar: 'lena1_kdgobc',
    avatarHovered: 'lena2_otcylo',
  },
  {
    name: 'Vitalii Ovsiannikov',
    role: 'Frontend Developer',
    photo: 'vitalii',
    contacts: null,
    description: 'If the community is an algorithm, she’s the key that makes it run!',
    avatar: 'vitalii1_vy8c8y',
    avatarHovered: 'vitalii2_yuedtl',
  },
  {
    name: 'Elizaveta Bychkova',
    role: 'Backend Engineer',
    photo: 'lisa',
    contacts: null,
    description: 'If the community is an algorithm, she’s the key that makes it run!',
    avatar: 'liza1_bjhk5b',
    avatarHovered: 'liza2_kfzzwg',
  },
  {
    name: 'Ilina Nigmatullina',
    role: 'Product Manager',
    photo: 'ilina',
    contacts: null,
    description: 'If the community is an algorithm, she’s the key that makes it run!',
    avatar: 'ilina1_iibssv',
    avatarHovered: 'ilina2_gdkqyl',
  },
  {
    name: 'Anastasia Toropova',
    role: 'HR Manager',
    photo: 'anastasia',
    contacts: null,
    description: 'If the community is an algorithm, she’s the key that makes it run!',
    avatar: 'nastya1_b9gnnp',
    avatarHovered: 'nastya2_qrmtsw',
  },

];
